### ISSUE TITLE
ACTIVIDAD 9

### ISSUE THREAD

**Issue by AricelCastro** [SistemasTecTlaxiaco/actividad-9-diagrama-de-clases-secuencia-equipo-naa#1]
[ACTIVIDAD 9 CS.pdf](https://github.com/user-attachments/files/18086446/ACTIVIDAD.9.CS.pdf)

**Comment by GibranVasquez** [comment]
27 
Bien hecho, hizo falta un poco más de detalle a los pasos e imágenes

**Comment by josealfredo79** [comment]
debes checar los resultados y las conclusiones ..por favor

**Comment by AricelCastro** [comment]
CORREGIDO

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
